# https://taskfile.dev

version: '3'

includes: 
  deps: deps.setup.conda-env.exe.yml
  
vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
      - task -l
    silent: true

  show-homedir-size:
    desc: _
    cmds:
      - du -sh ~
  
  show-vscode-proc:
    desc: _
    cmds:
      - ps -fade | grep vscode
    
